[tool.poetry]
name = "small-asc"
version = "0.9.6"
description = "A small Solr client"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.22.0"
ujson = "^5.1.0"

[tool.poetry.dev-dependencies]
ipython = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
