[tool.poetry]
name = "small-asc"
version = "0.9.2"
description = "A small Solr client"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.21.0"
ujson = "^5.1.0"

[tool.poetry.dev-dependencies]
ipython = "^7.24.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
