[tool.poetry]
name = "small-asc"
version = "0.12.3"
description = "A small Solr client"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
orjson = "^3.8.5"
aiohttp = {extras = ["speedups"], version = "^3.8.4"}

[tool.poetry.dev-dependencies]
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"