[tool.poetry]
name = "small-asc"
version = "0.4.0"
description = "A small asynchronous Solr client"
authors = ["Andrew Hankinson <andrew.hankinson@rism.digital>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.18.2"
ujson = "^4.0.2"

[tool.poetry.dev-dependencies]
ipython = "^7.24.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
